### ISSUE TITLE
Didn't run it

### ISSUE THREAD

**Issue by guanfaqian** [salu133445/musegan#22]
I want to run it,but when I ran the'main.py' that say 
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from config import CONFIG
  File "/media/gfq/dataset/museGAN/musegan/config.py", line 306, in <module>
    SETUP['preset_d'])))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named discriminator.proposed

**Comment by salu133445** [comment]
Seems like it failed to import the preset discriminator network architecture. The `config.py` assumes that the presets is at 'REPO_DIR/musegan/presets/discriminator/proposed.py ' (REPO_DIR is the directory where you can find `config.py` and where you run `main.py`). We uses relative path in current version, so you have to run the `main.py` in REPO_DIR (i.e. `python ./main.py`).

```python
IMPORTED = importlib.import_module(
    '.'.join(('musegan', SETUP['model'], 'presets', 'discriminator',
              SETUP['preset_d'])))
CONFIG['model']['net_d'] = IMPORTED.NET_D
```

You can also change it to absolute path to avoid such problems so that you can run `main.py` at any working directory you want. Your contribution is welcome.

**Comment by salu133445** [comment]
My guess is that you forgot to set the correct values for `CONFIG['model']['num_sample']` and `CONFIG['model']['sample_grid']`in `config.py`. The product of the latter must equal to the former.
