### ISSUE TITLE
Best way to generate track conditioned output

### ISSUE THREAD

**Issue by aaronrmm** [salu133445/musegan#44]
Given all the different versions and sets of training data, what do you see as the fastest way to get a trained model running that supports track conditioning? This could include training a model, or even implementing track conditioning into one of the newer versions. Whatever you think might be fastest. Thanks!

**Comment by salu133445** [comment]
We now support track conditional generation in v3. But note that the model design and network architecture are different from the paper. Please refer to exp/accompaniment/bass/params.yaml for an example parameter setting. Pretrained models are available as well.

**Comment by aaronrmm** [comment]
I'm still having trouble. In v3 I've got the model successfully loading the checkpoint and running inference on bass with an npy as the input track. It runs but changing the input track doesn't change the output. We have:

#params 
is_conditional: true
is_accompaniment: true
condition_track_idx: 3 # This is the index our track is on.

# Data
data_source: 'npy'
data_root: ~
data_filename: input_music.npy

**Comment by salu133445** [comment]
If you have downloaded the pretrained models, you only need to change the data source/file in `./exp/accompaniment/bass/config.yaml` and run `./scripts/run_inference.sh ./exp/accompaniment/bass/`. Values in `params.yaml` must not be changed when you are using pretrained models.

If this is not the case, please provide more information including the command you used and any values in `params.yaml` and `config.yaml` that you modified so that I can diagnose your problem. Thanks.

**Comment by Han1018** [comment]
Thank you doing open source project for generating multitrack music. I have a extend question is when I use track condition method to predict , I'll got series of 25 songs. how do I change this configuration.
