### ISSUE TITLE
復現過程中遇到的小問題

### ISSUE THREAD

**Issue by lovelyBullshit** [salu133445/musegan#62]
您好，我們正嘗試使用pytorch復現您的工作。
但是訓練結果似乎並不理想，訓練后，一個batch內的所有生成音樂都幾乎完全相同，而且每段音樂內的4個小節也完全相同。
在復現過程中我們主要參考的是src/musegan/preset中的model.py, train.py,以及您的G與D的default網絡結構，請問是否有什麼重要的信息被我們遺漏了？另外，在您的代碼中並未找到關於生成時序性的代碼，請問最後生成音樂的時序相關性是如何保證的呢？煩請指正。

謝謝！

**Comment by salu133445** [comment]
Did you use gradient penalties? If not so, it might easily lead to the so-called _mode collapse_ issue. In the current model, temporal dependency is handled by the transposed convolutional layer in the generator.

**Comment by salu133445** [comment]
Close the issue for there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
