### ISSUE TITLE
Questions about "train_x_lpd_5_phr.npz"

### ISSUE THREAD

**Issue by shaform** [salu133445/musegan#63]
Why is it the case that the shape is `[102378,      4,     48,     84,      5]`?
It seems that it only has 48 time steps, but the paper seems to indicate that there should be 96 steps?
Also, why are there 102,378 entries? Are these 102,378 unique songs? I couldn't find the number 102,378 mentioned anywhere in the paper or on the project page.

**Comment by salu133445** [comment]
The data array is reshaped into `(n_samples, n_bars, n_timesteps, n_pitchs, n_tracks)`. And yes, in this version we use only 48 time steps as we have figured out a better way to parse the pianorolls so that we do not actually need 96 time steps per bar.

The training data is collected from the [lpd-cleansed](https://salu133445.github.io/lakh-pianoroll-dataset/dataset) dataset, which only contains 21,425 pianorolls from different songs. Hence, we extract multiple four-bar phrases for each song, and the number of phrases extracted can be different.

**Comment by shaform** [comment]
Thanks for the clarification!

**Comment by Liujingxiu23** [comment]
@salu133445  Could you please give a http address to download the train data cuase my linux service can not be connected to internet? Thanks a lot
