### ISSUE TITLE
discriminator and generator loss convergence

### ISSUE THREAD

**Issue by techcentaur** [salu133445/musegan#66]
In the museGAN paper, the negative critic loss is said to be converging around 10 to the power of 8.

I am training the model on my own, and my generator loss is oscillating around zero, an e.g. history is
```console
   1  |  104/ 180 |  67.79 |      60.750362 |     -16.181793
   1  |  105/ 180 |  67.73 |      62.146736 |      40.134007
   1  |  106/ 180 |  67.83 |      74.526474 |      33.856094
   1  |  107/ 180 |  67.66 |      59.294342 |     -21.401932
   1  |  108/ 180 |  67.92 |     115.995209 |      94.344543
   1  |  109/ 180 |  68.00 |     156.438293 |     224.599945
   1  |  110/ 180 |  68.32 |      54.108414 |     -35.459709
```
sometimes it is positive, and sometimes negative. And also discriminator loss (negative) is coming around 50-100.

So my question is?
1. Where should ideally generator and discriminator losses converge?
2. I am sensing, I should increase the parameter of the generator, is it a right approach?

Thank you in advance. :)

**Comment by salu133445** [comment]
The values look reasonable to me. For GANs, the absolute values for the losses are not that meaningful, according to our experience. Both the generator and the discriminator losses will finally oscillate around some numbers and the absolute values usually mean nothing.

You can certainly try changing the architectures or the number of parameters in the discriminator or the generator, while you should evaluate the resulting models with other metrics rather than the final losses.

On the other hand, the values we reported in the paper are calculated in a different way from the current version, and hence they are not comparable.
